name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Building and pushing the Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: | 
            joaodev599/python-api:v${{ github.run_number }}
            joaodev599/python-api:latest

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2
    
      
    
