name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run Tests
        run: |
          cd ./src
          python manage.py test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Building and pushing the Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: | 
            joaodev599/python-api:v${{ github.run_number }}
            joaodev599/python-api:latest
  
  Infrastructure:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.0"

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Plan Terraform Changes
        run: |
          cd terraform
          terraform plan -out=tfplan

      - name: Apply Terraform Changes
        run: |
          cd terraform
          terraform apply -auto-approve
      
      - name: Destroy Terraform Changes
        run: |
          cd terraform
          terraform destroy --auto-approve

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2
    
      
    
