name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run Tests
        run: |
          cd ./src
          python manage.py test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Building and pushing the Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          file: ./src/Dockerfile
          tags: | 
            joaodev599/python-api:v${{ github.run_number }}
            joaodev599/python-api:latest
  
  Infrastructure:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.6.0"

      - name: Generate SSH Key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -C "github-actions" -f ~/.ssh/id_rsa -N ""
      
      # - name: Save SSH Private Key
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ssh-private-key
      #     path: ~/.ssh/id_rsa
      #     retention-days: 1
      
      # - name: Retrieve SSH Private Key
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: ssh-private-key
      #     path: ~/.ssh

      # - name: Set SSH Key Permissions
      #   run: chmod 600 ~/.ssh/id_rsa

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init
      
      - name: Create Terraform Data Directory
        run: |
          sudo mkdir -p /terraform_data
          sudo chmod 777 /terraform_data

      - name: Plan Terraform Changes
        run: |
          cd terraform
          terraform plan -out=tfplan

      - name: Apply Terraform Changes
        run: |
          cd terraform
          terraform apply -auto-approve
      
      - name: Destroy Terraform Changes
        run: |
          cd terraform
          terraform destroy --auto-approve

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4.2.2
    
      
    
